add UserSelect
tkalmykova/task-manager pull request #20
Opened 2020-05-27 11:49 UTC by tkalmykova

2020-06-02 10:20 UTC, pn-y requested changes

2020-06-02 10:20 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:name, :description,:author_id, :assignee_id, :state_event)
Уверен что автора можно менять?

2020-06-02 10:20 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +            <UserSelect
Т.е. чувак возьмет и скажет "автор этой таски теперь - Вася"? Выглядит неправильно.

2020-06-02 16:06 UTC, tkalmykova commented on app/javascript/components/AddPopup/AddPopup.js
> +            <UserSelect
Согласна) но в задании было написано сделать сделать селект для автора)Правильно понимаю, что нужно оставить селект только для assignee?

2020-06-02 16:09 UTC, tkalmykova commented on app/javascript/components/AddPopup/AddPopup.js
> +            <UserSelect
![image](https://user-images.githubusercontent.com/35146827/83543060-e2b62580-a50c-11ea-89be-c087764dcfea.png)

2020-06-03 10:23 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +            <UserSelect
Ага, поправим. Само задание ведь не так называется :)

2020-06-03 10:33 UTC, pn-y requested changes

2020-06-03 10:33 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +            {/* <UserSelect
Выпили закомментированный код

2020-06-03 10:33 UTC, pn-y commented on app/javascript/components/EditPopup/EditPopup.js
> +              {/* <UserSelect
И тут

2020-06-03 10:33 UTC, pn-y commented on app/javascript/components/EditPopup/EditPopup.js
> +              <UserSelect
Кмк будет лучше унести UserSelect внутрь формы. А то получается весьма странно, вроде и форма, а есть изменяемые поля вне нее.

2020-06-03 10:33 UTC, pn-y commented on app/javascript/components/EditPopup/EditPopup.js
> +                value={isLoading ? null : task.assignee}
Сюда же выполнение не дойдет если будет флаг isLoading

2020-06-03 10:33 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> +  const isLoading = isNil(task);
А тут может быть nil вообще? На 23 строке же ты говоришь что будут дефолтные аттрибуты.

2020-06-03 10:33 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      author: '',
А почему это строки?

2020-06-04 05:41 UTC, tkalmykova commented on app/javascript/forms/TaskForm.js
> +      author: '',
Исправила, но так и не поняла, почему здесь строки не подходят, можешь пояснить?

2020-06-04 10:39 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      author: '',
@tkalmykova если мы исходим из того что author это всегда объект - он всегда должен быть объектом. Смена типа - это не очень хорошо, и может ломать тебе проверки проп тайпов, например.

2020-06-04 10:45 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      author: '',
https://reactjs.org/docs/forms.html#controlled-input-null-value вот подробности. Поэтому перепроверь пжлст чтоб у тебя компоненты не скакали между controlled-uncontrolled и небыло ворнингов

2020-06-06 19:09 UTC, helmq requested changes

2020-06-06 19:09 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
> +        value={task.assignee}
Нужно использовать презентер

2020-06-06 19:09 UTC, helmq commented on app/javascript/components/EditPopup/components/Form/Form.js
> +  task: PropTypes.shape({
У тебя же уже описана форма объекта в TaskPresenter

2020-06-08 12:25 UTC, tkalmykova commented on app/javascript/forms/TaskForm.js
> +      author: '',
![image](https://user-images.githubusercontent.com/35146827/84029426-6b1c4680-a9a3-11ea-84a7-e377308ff89d.png)
Пришлось вернуть пустую строку, так  как появилась ошибка. Или нужно использовать "undefined" , и если да, можешь объяснить почему?

2020-06-10 12:04 UTC, helmq approved these changes

2020-06-10 13:00 UTC, merged