Feature/travis
tkalmykova/task-manager pull request #22
Opened 2020-06-03 10:09 UTC by tkalmykova

2020-06-04 10:51 UTC, pn-y requested changes

2020-06-04 10:51 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    params.require(:task).permit(:name, :description, :assignee_id, :state_event)
будто бы это не относится к текущему мр

2020-06-04 10:51 UTC, pn-y commented on app/javascript/components/AddPopup/AddPopup.js
> -            <UserSelect
и это

2020-06-04 10:51 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +import 'material-design-lite/material.js';
?! жс импортится в рубишный тест?!

2020-06-10 12:07 UTC, helmq requested changes

2020-06-10 12:07 UTC, helmq commented on test/controllers/web/boards_controller_test.rb
> +
Зачем здесь и в других файлах дополнительные пустые строки?

2020-06-10 14:51 UTC, helmq approved these changes

2020-06-11 04:29 UTC, merged