add css to bundle
tkalmykova/task-manager pull request #26
Opened 2020-06-08 11:17 UTC by tkalmykova

2020-06-10 15:07 UTC, helmq requested changes

2020-06-10 15:07 UTC, helmq commented on app/controllers/api/v1/tasks_controller.rb
>      tasks = Task.all.
`all` не нужен, `result` вернет нужную коллекцию

2020-06-10 15:11 UTC, helmq commented on config/initializers/rollbar.rb
> +  config.access_token = ENV['ROLLBAR_ACCESS_TOKEN']
Токен лежит в config vars на хероку?(уточняю)

2020-06-11 04:33 UTC, tkalmykova commented on config/initializers/rollbar.rb
> +  config.access_token = ENV['ROLLBAR_ACCESS_TOKEN']
да

2020-06-11 05:06 UTC, helmq approved these changes

2020-06-11 05:23 UTC, merged