Feature/forgot password
tkalmykova/task-manager pull request #29
Opened 2020-06-25 08:39 UTC by tkalmykova

2020-06-25 19:20 UTC, pn-y requested changes

2020-06-25 19:20 UTC, pn-y commented on app/controllers/api/v1/password_updates_controller.rb
> +    password_update_form.token = params[:token]
А почему токен вне password_update_form?

2020-06-25 19:20 UTC, pn-y commented on app/controllers/api/v1/password_updates_controller.rb
> +class Api::V1::PasswordUpdatesController < Api::V1::ApplicationController
А ради какой цели разнесено это в два разных контроллера?
По сути же идет работа с PasswordReset, где мы его "создаем" для генерации токена, и "аптейтим" для задания нового пароля

2020-06-25 19:20 UTC, pn-y commented on db/migrate/20200624051651_add_password_reset_columns_to_users.rb
> +    add_index :users, :password_reset_token, unique: true
👍

2020-06-26 07:26 UTC, tkalmykova commented on app/controllers/api/v1/password_updates_controller.rb
> +class Api::V1::PasswordUpdatesController < Api::V1::ApplicationController
Я исходила из того, что у меня две отдельные формы для ресета и апдэйта, на каждую своя точка входа и свой веб-контроллер, поэтому для соответствия сделала так. к апдейту же мы приступаем только после ресета пароля и получения ссылки из письма.

2020-07-01 10:57 UTC, tkalmykova commented on app/controllers/api/v1/password_updates_controller.rb
> +    password_update_form.token = params[:token]
Исправила.

2020-07-06 20:25 UTC, artempartos commented on app/controllers/api/v1/password_updates_controller.rb
> +class Api::V1::PasswordUpdatesController < Api::V1::ApplicationController
в целом разные формы можно использовать в одном контейнере

2020-07-06 20:26 UTC, artempartos approved these changes

2020-07-07 10:39 UTC, merged